const betterAuthLocalizationUA = {
  missingCaptchaResponse: "Відсутня відповідь CAPTCHA",
  byContinuingYouAgree: "Продовжуючи, ви погоджуєтесь з",
  protectedByRecaptcha: "Цей сайт захищено reCAPTCHA.",
  termsOfService: "Умовами користування",
  privacyPolicy: "Політикою конфіденційності",
  uploadAvatar: "Завантажити аватар",
  passwordTooLong: "Пароль занадто довгий",
  passwordTooShort: "Пароль занадто короткий",
  sessionExpired: "Сесія закінчилась",
  sessionNotFresh: "Ваша сесія застаріла. Будь ласка, увійдіть знову.",
  passwordInvalid: "Неправильний пароль",
  invalidEmailOrPassword: "Неправильний email або пароль",
  goBack: "Повернутись",
  verifyYourEmailDescription:
    "Будь ласка, підтвердіть свою email адресу. Перевірте поштову скриньку на наявність листа підтвердження. Якщо ви не отримали лист, натисніть кнопку нижче, щоб повторно надіслати.",
  verifyYourEmail: "Підтвердіть ваш email",
  signInUsernamePlaceholder: "Ім'я користувача або email",
  usernamePlaceholder: "Ім'я користувача",
  usernameInstructions: "Будь ласка, використовуйте максимум 32 символи.",
  usernameDescription:
    "Введіть ім'я користувача, яке ви хочете використовувати для входу.",
  username: "Ім'я користувача",
  updatedSuccessfully: "Успішно оновлено",
  unlink: "Від'єднати",
  sendVerificationCode: "Надіслати код підтвердження",
  twoFactorTotpLabel: "Зіскануйте QR код вашим автентифікатором",
  twoFactorPrompt: "Двофакторна автентифікація",
  twoFactorDisabled: "Двофакторну автентифікацію відключено",
  twoFactorEnabled: "Двофакторну автентифікацію увімкнено",
  twoFactorEnableInstructions:
    "Будь ласка, введіть ваш пароль для увімкнення 2FA",
  twoFactorDisableInstructions:
    "Будь ласка, введіть ваш пароль для відключення 2FA.",
  twoFactorCardDescription:
    "Додайте додатковий рівень безпеки до вашого аккаунту.",
  twoFactorDescription:
    "Будь ласка, введіть ваш одноразовий пароль для продовження",
  twoFactorAction: "Підтвердити код",
  twoFactor: "Двофакторна",
  trustDevice: "Довіряти цьому пристрою",
  switchAccount: "Перемикнути аккаунт",
  security: "Безпека",
  save: "Зберегти",
  settings: "Налаштування",
  setPasswordDescription:
    "Натисніть кнопку нижче, щоб отримати email для налаштування паролю для вашого аккаунту.",
  setPassword: "Встановити пароль",
  sessionsDescription:
    "Керуйте вашими активними сесіями та відкликайте доступ.",
  sessions: "Сесії",
  signUpEmail: "Перевірте ваш email на наявність посилання підтвердження.",
  signUpDescription: "Введіть вашу інформацію для створення аккаунту",
  signUpAction: "Створити аккаунт",
  signUp: "Реєстрація",
  signOut: "Вийти",
  signInWith: "Увійти за допомогою",
  signInUsernameDescription:
    "Введіть ваше ім'я користувача або email нижче для входу в аккаунт",
  signInDescription: "Введіть ваш email нижче для входу в аккаунт",
  signInAction: "Увійти",
  signIn: "Вхід",
  apiKey: "API ключ",
  deleteApiKeyConfirmation: "Ви впевнені, що хочете видалити цей API ключ?",
  deleteApiKey: "Видалити API ключ",
  revoke: "Відкликати",
  requestFailed: "Запит не вдався",
  resetPasswordSuccess: "Пароль успішно скинуто",
  resetPasswordInvalidToken: "Неправильне посилання для скидання паролю",
  resetPasswordDescription: "Введіть ваш новий пароль нижче",
  resetPasswordAction: "Зберегти новий пароль",
  resetPassword: "Скинути пароль",
  resendVerificationEmail: "Повторно надіслати email підтвердження",
  resendCode: "Повторно надіслати код",
  rememberMe: "Запам'ятати мене",
  recoverAccountDescription:
    "Будь ласка, введіть резервний код для доступу до вашого аккаунту",
  recoverAccountAction: "Відновити аккаунт",
  recoverAccount: "Відновлення аккаунту",
  providersDescription: "Підключіть ваш аккаунт до стороннього сервісу.",
  providers: "Провайдери",
  passwordsDoNotMatch: "Паролі не співпадають",
  passwordRequired: "Пароль обов'язковий",
  passwordPlaceholder: "Пароль",
  password: "Пароль",
  create: "Створити",
  noExpiration: "Без терміну дії",
  expires: "Закінчується",
  neverExpires: "Ніколи не закінчується",
  apiKeyCreatedDescription:
    "Будь ласка, скопіюйте ваш API ключ та збережіть його в безпечному місці. З міркувань безпеки ми не можемо показати його знову.",
  apiKeyCreated: "API ключ створено",
  apiKeyNamePlaceholder: "Новий API ключ",
  createApiKeyDescription:
    "Введіть унікальну назву для вашого API ключа, щоб відрізнити його від інших ключів.",
  createApiKey: "Створити API ключ",
  apiKeysInstructions:
    "Генеруйте API ключі для програмного доступу до вашого аккаунту.",
  apiKeysDescription: "Керуйте вашими API ключами для безпечного доступу.",
  apiKeys: "API ключі",
  passkeysInstructions:
    "Безпечно отримайте доступ до вашого аккаунту без паролю.",
  passkeysDescription: "Керуйте вашими ключами доступу для безпечного входу.",
  passkeys: "Ключі доступу",
  passkey: "Ключ доступу",
  orContinueWith: "Або продовжте з",
  oneTimePassword: "Одноразовий пароль",
  newPasswordRequired: "Новий пароль обов'язковий",
  newPasswordPlaceholder: "Новий пароль",
  newPassword: "Новий пароль",
  namePlaceholder: "Ім'я",
  nameInstructions: "Будь ласка, використовуйте максимум 32 символи.",
  nameDescription:
    "Будь ласка, введіть ваше повне ім'я або відображуване ім'я.",
  name: "Ім'я",
  emailOTPVerificationSent:
    "Будь ласка, перевірте ваш email на наявність коду підтвердження.",
  emailOTPDescription: "Введіть ваш email для отримання коду",
  emailOTPVerifyAction: "Підтвердити код",
  emailOTPSendAction: "Надіслати код",
  emailOTP: "Email код",
  magicLinkEmail: "Перевірте ваш email на наявність магічного посилання",
  magicLinkDescription: "Введіть ваш email для отримання магічного посилання",
  magicLinkAction: "Надіслати магічне посилання",
  magicLink: "Магічне посилання",
  link: "Посилання",
  invalidTwoFactorCookie: "Неправильний двофакторний cookie",
  forgotPasswordLink: "Забули пароль?",
  forgotPasswordEmail:
    "Перевірте ваш email на наявність посилання для скидання паролю.",
  forgotPasswordDescription: "Введіть ваш email для скидання паролю",
  forgotPasswordAction: "Надіслати посилання скидання",
  forgotPassword: "Забули пароль",
  forgotAuthenticator: "Забули автентифікатор?",
  isTheSame: "той самий",
  isRequired: "обов'язковий",
  isInvalid: "неправильний",
  error: "Помилка",
  enable: "Увімкнути",
  emailVerification:
    "Будь ласка, перевірте ваш email на наявність посилання підтвердження.",
  emailVerifyChange: "Будь ласка, перевірте ваш email для підтвердження змін.",
  emailRequired: "Email адреса обов'язкова",
  emailPlaceholder: "m@example.com",
  emailIsTheSame: "Email той самий",
  emailInvalid: "Email адреса неправильна",
  emailInstructions: "Будь ласка, введіть правильну email адресу.",
  emailDescription:
    "Введіть email адресу, яку ви хочете використовувати для входу.",
  email: "Email",
  done: "Готово",
  dontHaveAnAccount: "Немає аккаунту?",
  disabledCredentialsDescription: "Оберіть провайдера для входу в ваш аккаунт",
  disable: "Відключити",
  deleteAccountNotFresh:
    "Ви повинні нещодавно увійти в систему, щоб видалити ваш аккаунт.",
  deleteAccountSuccess: "Ваш аккаунт було видалено.",
  deleteAccountVerify:
    "Будь ласка, перевірте ваш email для підтвердження видалення вашого аккаунту.",
  deleteAccountInstructions:
    "Будь ласка, підтвердіть видалення вашого аккаунту. Ця дія необоротна, тому будьте обережні.",
  deleteAccountDescription:
    "Назавжди видалити ваш аккаунт та весь його вміст. Ця дія необоротна, тому будьте обережні.",
  deleteAccount: "Видалити аккаунт",
  deleteAvatar: "Видалити аватар",
  delete: "Видалити",
  currentSession: "Поточна сесія",
  currentPasswordPlaceholder: "Поточний пароль",
  currentPassword: "Поточний пароль",
  continue: "Продовжити",
  copyAllCodes: "Скопіювати всі коди",
  copyToClipboard: "Скопіювати в буфер обміну",
  copiedToClipboard: "Скопійовано в буфер обміну",
  continueWithAuthenticator: "Продовжити з автентифікатором",
  confirmPasswordRequired: "Підтвердження паролю обов'язкове",
  confirmPasswordPlaceholder: "Підтвердити пароль",
  confirmPassword: "Підтвердити пароль",
  changePasswordSuccess: "Ваш пароль було змінено.",
  changePasswordInstructions: "Будь ласка, використовуйте мінімум 8 символів.",
  changePasswordDescription: "Введіть ваш поточний пароль та новий пароль.",
  changePassword: "Змінити пароль",
  cancel: "Скасувати",
  backupCodeAction: "Відновити аккаунт",
  backupCode: "Резервний код",
  backupCodePlaceholder:
    "Введіть один з ваших резервних кодів. Після використання кожен код можна використати лише один раз, і він буде анульований після використання.",
  backupCodesDescription:
    "Збережіть ці резервні коди в безпечному місці. Ви можете використовувати їх для доступу до вашого аккаунту, якщо втратите метод двофакторної автентифікації.",
  backupCodes: "Резервні коди",
  backupCodeRequired: "Резервний код обов'язковий",
  avatarInstructions: "Аватар необов'язковий, але наполегливо рекомендується.",
  avatarDescription:
    "Натисніть на аватар, щоб завантажити власний з ваших файлів.",
  avatar: "Аватар",
  alreadyHaveAnAccount: "Вже маєте аккаунт?",
  addPasskey: "Додати ключ доступу",
  addAccount: "Додати аккаунт",
  accountsInstructions: "Увійти в додатковий аккаунт.",
  accountsDescription: "Керуйте вашими поточними аккаунтами, в які ви увійшли.",
  accounts: "Аккаунти",
  account: "Аккаунт",
} as const;

export default betterAuthLocalizationUA;
